name: Deploy to VM

on:
  push:
    branches:
      - master  # Adjust to the branch you want for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy changes to VM
      env:
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        REMOTE_HOST: ${{ secrets.SSH_IP }}
        REMOTE_PATH: "/var/www/html/ademnea_website"  # Path to your project on the VM
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << EOF
          cd $REMOTE_PATH
          # Fetch latest master and reset local files to match exactly
          git fetch origin master
          git reset --hard origin/master

